"""断板报告生成器"""
from .base_reporter import BaseReporter


class DBReporter(BaseReporter):
    """断板报告生成器

    继承自 BaseReporter，实现断板分析报告的生成逻辑
    """

    report_type = "db"

    def build_report(self, date_str: str, stock_info: str, analysis_result: str, **kwargs) -> str:
        """构建断板分析报告

        :param date_str: 日期字符串
        :param stock_info: 股票信息列表
        :param analysis_result: 分析结果（包含分类统计、未来空间排序、个股分析）
        :param kwargs: 其他参数
        :return: 格式化后的报告内容
        """
        total_stocks = kwargs.get('total_stocks', len([line for line in stock_info.split('\n') if line.strip()]))

        return f"""# 📉 每日断板股票分析报告

**日期**: {date_str}
**当日断板总数**: {total_stocks} 只
**分析股票数量**: {len([line for line in stock_info.split('\n') if line.strip()])} 只

---

## 📋 断板股票列表

{stock_info}

---

{analysis_result}

---

风险提示：本文不构成任何投资建议，股市有风险，入市需谨慎。

---

*Generated by 股票分析助手*
"""
