"""炸板报告生成器"""
from .base_reporter import BaseReporter


class ZBReporter(BaseReporter):
    """炸板报告生成器

    继承自 BaseReporter，实现炸板分析报告的生成逻辑
    """

    report_type = "zb"

    def build_report(self, date_str: str, stock_info: str, analysis_result: str, **kwargs) -> str:
        """构建炸板分析报告

        :param date_str: 日期字符串
        :param stock_info: 股票信息列表
        :param analysis_result: 分析结果
        :param kwargs: 其他参数
        :return: 格式化后的报告内容
        """
        total_stocks = kwargs.get('total_stocks', len([line for line in stock_info.split('\n') if line.strip()]))

        return f"""# 💥 每日炸板股票分析报告

**日期**: {date_str}
**当日炸板总数**: {total_stocks} 只
**分析股票数量**: {len([line for line in stock_info.split('\n') if line.strip()])} 只

---

## 📋 炸板股票列表

{stock_info}

---

## 📊 分析结果

{analysis_result}

---

*Generated by 股票分析助手*
"""
